### ISSUE TITLE
partial replication

### ISSUE THREAD

**Issue by davidmarkclements** [ssbc/scuttlebot#124]
apologies if this has already been considered, not seeing it in issues here or secure-scuttlebott

its feasable that over time peers could become quite fat with history, 
history that you might want to keep, but not frequently use.

What if you could have thin peers that replicate upwards from a point
in a chain, and then prune their chains when they pass a certain length

If I want the latest information, I can ask any peer, if I want to dig deep into historical
records the  I ask a fat peer, the thin peer could potentially reedirect to a fat peer

this may violate the concept of all peers being equal, but all peers woulld still have the option
of being equal there's obviously no external encforcement of peer type beyond normal constraints (such as not having the required disk space for a fat peer)

**Comment by dominictarr** [comment]
No problem, but yes we have discussed this sort of thing. It would be necessary to improve the validation algorithm to use merkle trees, because you need to be able to verify that a particular message is actually part of the log.

https://github.com/ssbc/secure-scuttlebutt/issues/27

**Comment by pfraze** [comment]
This is a topic that needs to be studied in-depth, so I'm glad to open another discussion on it. We have discussed using different replication strategies (https://github.com/ssbc/phoenix/issues/170) which would result in partial replication. There's also been discussion about using merkle-trees to allow partial replication while maintaining the blockchain verification.

One challenge that concerns me is how to choose the subset to replicate. Though each log-entry exists in isolation as an immutable object, most applications will construct stateful records from the entries by aggregating them. Therefore, a thin peer would need to either only deal in log-entries that exist in total isolation (not super feasible) or it would need to use causal links in order to choose subsets which relate to each other, which is what is discussed in https://github.com/ssbc/phoenix/issues/170.

**Comment by dominictarr** [comment]
@pfraze we'd probably want msg links to have the feed and the sequence number on them so it's easy to find that particular message.

**Comment by pfraze** [comment]
@dominictarr that'd add another 52 bytes (at least) for the feed hash. You may be right but that's going to add up.

**Comment by dominictarr** [comment]
@pfraze true, but we can just raise the size limit if we have a really good reason.

**Comment by davidmarkclements** [comment]
What if you only store part of the feed hash... say the first 4 and last 4 bytes? If for any reason that happens to match more than one feed, the merkle root + message hash should be able to qualify the correct feed

**Comment by dominictarr** [comment]
@davidmarkclements in this case that would probably be okay since it's really just a hint. Although, it is useful to have exact. I bet there will be uses from being able to tell two feeds interact. Bytes are cheap.
