### ISSUE TITLE
FAQ / wiki (post here when you make changes to wiki, for notifications)

### ISSUE THREAD

**Issue by dominictarr** [ssbc/scuttlebot#145]
to prepare for my talk tomorrow I've been working on an FAQ

https://github.com/ssbc/scuttlebot/wiki/FAQ

will be useful later, I'm sure ;)

**Comment by pfraze** [comment]
hey, this is great! :+1: some proposals to add...

we may want to include some distributed-system stuff, maybe right after "Consistent Data":

**Is SSB highly available (AP) or highly consistent (CP)?**

SSB is highly-available (AP). Devices can create messages while offline, then synchronize later. This means all data is eventually-consistent.

**Can I know if I have the latest messages from somebody?**

No, because it's possible for devices to drop and continue operating (a network "partition.") There's a proposal to used signed pings to measure the "freshness" of a feed, however this could only be used in small groups of interested peers.

**Is there a global order in SSB?**

No. Feeds maintain a strict internal order, and messages include UTC timestamps, but this isn't enough to know the order of all messages in the network. (The timestamps can be skewed or forged.) It is possible to determine the "happens-before" relationship using links, since a link is a content hash, it can only be created after the message is created.

---

also the section on links should be updated, it is possible to use arrays of links as well as a single object

**Comment by dominictarr** [comment]
@pfraze this is a wiki so just add stuff ;) (I did added these) prehaps the best way to do this,
is when you make a change post in this issue... because wiki edits do not have notifications otherwise.

**Comment by dominictarr** [comment]
lets put everything on one page until it gets too big.

**Comment by pfraze** [comment]
ok yeah, just mention the change made here

**Comment by dominictarr** [comment]
linked to petnames paper http://www.skyhunter.com/marcs/petnames/IntroPetNames.html

**Comment by dominictarr** [comment]
added backlinks section

**Comment by ahdinosaur** [comment]
:+1: to more documentation about ssb. i see ssb as a decentralized data protocol being created by the Mad Science Karass that is competing against other similar protocols being created by other entities, most important of which is the Great Committee Standards Bodies like those of the W3C. if we want to succeed, i reckon we need to provide documentation at least as good as our competitors.

examples of competing protocols (that i'm aware of):
- [Linked Data Platform](http://www.w3.org/2012/ldp/wiki/Main_Page)
- [Social Web](http://www.w3.org/Social/WG)
- [Matrix](http://matrix.org/)
- [FOSP](https://rawgit.com/maufl/fosp-specification/master/fosp.html)

**Comment by dominictarr** [comment]
I added another page about sybil attacks https://github.com/ssbc/scuttlebot/wiki/design-challenge:-sybil-attack-%5C--spam

**Comment by dominictarr** [comment]
added page on decentralization and avoiding singletons https://github.com/ssbc/scuttlebot/wiki/design-challenge:-avoid-centralization-and-singletons

**Comment by dominictarr** [comment]
Added page that summarizes the design of various secure-channel protocols
https://github.com/ssbc/scuttlebot/wiki/secure-private-channels:-the-good,-the-bad,-and-the-ugly

**Comment by ootoovak** [comment]
Added some basic steps to getting on the SSB network with Scuttlebot: https://github.com/ssbc/scuttlebot/wiki/Getting-on-the-Scuttlebot-network

**Comment by dominictarr** [comment]
@ootoovak good work! This is also a good place to encourage people to post an issue if they encounter an error

**Comment by dominictarr** [comment]
closing, since the wiki is now the https://github.com/ssbc/ssb-docs repo
