### ISSUE TITLE
require a size on ext-links before fetching blob, and enforce a size-limit

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#179]
The blob sync is very optimistic about its blob-downloading -- if it sees a blob, it downloads it! This makes the network easy to DoS by posting a bunch of large files.

One defensive step we can take is to impose a file-size limit. This would...
- Require a `size` attribute on ext links (in bytes). Phoenix already does this 
- Only auto-download blobs under a size limit. 1000x the message-size limit would be a simple scheme. (We're discussing 8kb for messages, so that would be 8mb.)

Of course there's still some ways to circumvent this:
- Post lots of files that fit in the limit
- Lie about the size

Both of these require some holistic strategies for resource-allotment and community policing. I suggest we handle them in separate issues.

**Comment by dominictarr** [comment]
I think there is already some code about this - if the file is not actually the size, it rejects it, and then doesn't get propagated through the network... to handle lots of files, we just need to throttle files per user (and rank downloadyness by friend distance, so you can't create lots of users either)

**Comment by pfraze** [comment]
looking at multihash, size-reject seems to be implemented in the `get` fn on the serverside, which is good but it needs to be in `add` too in case the server lies

i think a node will need to internally track if a blob comes back at the wrong size, otherwise it'll keep requesting the blob

we should give this whole system the docs treatment we discussed for #177

**Comment by dominictarr** [comment]
yup, it should be `multiblob.add({id: hash, size: length})` and abort if it's the wrong size.
