### ISSUE TITLE
running a pub server with `sbot server` with my own key by accident

### ISSUE THREAD

**Issue by myf** [ssbc/scuttlebot#228]
I am trying to run sbot server following this guide https://github.com/ssbc/scuttlebot#running-a-pub-server

The server starts after issuing `sbot server --host xxxxxxxx`, however after that it won't show any information of attempting to connect. `sbot whoami` and `sbot invite.create` returned with error/Then I decided to try it with my own key instead of a key that server generated and immediately i received some connection info. 

Today after some conversation with @dominictarr I realized that I shouldnt use my own key to run a server. I scratched the current set-up and regenerated the key and use that to run the server (on the same URL). 

Now my question is: does this settles everything? or does that mean whoever followed me will be followed by anyone I gave the invite to since my key is in the trusted network ?

**Comment by dominictarr** [comment]
@myf thanks, how did you run `whoami` and `invite.create` commands? these need to be run from the server, but prehaps that wasn't sufficiently clear in the documentation.

I've updated i few things, how does this look:

https://github.com/ssbc/scuttlebot/compare/master...dominictarr-patch-1?quick_pull=1

@pfraze did you add the thing about `--host` you don't actually need that, because sbot knows when it has a public ip address.

**Comment by pfraze** [comment]
@dominictarr I dont recall, but I mightve. So long as we're confident in the public ip addr code, that works for me.

**Comment by dominictarr** [comment]
@pfraze I havn't set a host on my pub and it has been working fine.

**Comment by dominictarr** [comment]
oops, I linked to a PR that wasn't complete: https://github.com/ssbc/scuttlebot/pull/229

**Comment by myf** [comment]
@dominictarr did just that, opened another window in the same server inquiring whoami. it wasn't working for some reason. I think it could be a fluke
