### ISSUE TITLE
Keep connection alive

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#243]
We had this problem in the past, I don't know if the solution got lost in the `secret-stack` rewrite.

After a period of inactivity, connections to sbot close. IIRC this is explicit (and good) behavior from `pull-inactivity`. However, I'm working on programs that run on the same device as sbot, which I want to keep persistently connected to scuttlebot (for instance, to listen for new messages).

How should we solve this? Should clients just send pings to keep the connection alive? Should clients listen for disconnects and autoreconnect? Should we let localhost clients stay alive?

**Comment by dominictarr** [comment]
I was looking into this, and the plan was to have more than one type of connection - long lived stable connections, and short lived, walker connections. the LL connections would provide real time updates, and the SL connections would broadcast. you'd connect to a few pubs, and when you get new messages, the SL walks the pubs you know, and ensures they have the latest messages, this way, it ensures you know all the messages!

but, I put of working on this because we only had one pub on the network. now there are two, so I'll probably pick this up again soonish.

@pfraze what are you using this for, can you explain your usecase.

**Comment by pfraze** [comment]
> I'm working on programs that run on the same device as sbot, which I want to keep persistently connected to scuttlebot (for instance, to listen for new messages).

Specifically https://github.com/pfraze/disco

**Comment by dominictarr** [comment]
@pfraze the readme is not very explainy. what is the desired behaviour with respect to this feature? how does it effect disco?

**Comment by pfraze** [comment]
I want to open a connection to scuttlebot, open a live log stream, and leave that log-stream open to receive new messages (so i can process them as sbot downloads them).

Because I can't expect perfect uptime from sbot, I'll have to listen for disconnects, and recreate the connection on disconnect.
So, if we want to keep behavior as-is, and let the sbot connection die regularly, we can.
But, it might perform better if we can keep the connection alive by  instructing sbot to put the connection in LL mode.

**Comment by dominictarr** [comment]
oh, right, you want to make the client connection be long lived, instead of the server killing it. this would certainly be doable.... right now both ends can kill the connection.

**Comment by pfraze** [comment]
Maybe make connections localhost LL by default?

**Comment by dominictarr** [comment]
I was just thinking that!

**Comment by pfraze** [comment]
Is it `pull-inactivity` doing this, inside `secret-stack`?

**Comment by dominictarr** [comment]
yes. I'd like to remove that, but currently the blob tests depend on that behaviour.
I'd really like to improve the blob replication, and the blob tests are a pain in the butt.
But I suspect i need to do another paper reading binge for that, also related is the gossip strategies and replication

**Comment by pfraze** [comment]
Ok, in the short-term can we just add a check against the remote-ip to disable it?

**Comment by NHQ** [comment]
*enhance*
