### ISSUE TITLE
Device-to-device proxy service

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#253]
Establishing direct connections between devices is difficult.
If it wasn't, we wouldn't be using Pubs.
If users are willing to let a Pub know some metadata, they could have the pub proxy ephemeral (off-log) messages to other devices.

Devices would maintain an active connection with the Pub, in order to stay reachable.
The Pub would offer a message-proxy API between the nodes, and the nodes would use this to arrange a confidential channel.
This channel could then be used to signal for WebRTC to establish a direct connection, if desired.

A proxy service would consume pub resources, and require moderation by the pub so that clients can't flood the pub or each other.

What metadata would be leaked?
- The pub would likely know the IPs of whichever two nodes it proxies between. This might be masked by _another_ proxy (or Tor) but, most people would just accept this sharing.
- [secret-handshake](https://github.com/dominictarr/secret-handshake) claims hiding of public keys of the participants. However, connections with the Pub are authenticated. The connecting-nodes could use different keys in the proxy connection, but some cryptographic identity will be known by the pub.
- Uptime would be leaked, since you have to keep an active connection with the pub to receive messages.

**Comment by dominictarr** [comment]
The pub server already knows the ip address that a peer connects on, so they have that metadata.
To do webrtc, a server informs a client what their ip/port is from the outside, so it does leak some metaphor.

They then need to share that with the peer they intend to connect to, but they could do that via end to end encryption, so the pub server wouldn't know *who* they are talking to, except prehaps via timing analysis.

Currently they'd need to do this via secret messages (which isn't forward secure) but it would be better to have ephemeral messaging, because that would be forward secure.

Another approach would be to have a relay service so that you may tunnel through a pub server

**Comment by dominictarr** [comment]
the relay service would be pretty simple to implement, actually.

**Comment by gardner** [comment]
Has this issue been addressed with the move to multiserver?

**Comment by cryptix** [comment]
I don't think so @gardner. I know that @clehner once worked one this but I'm unsure where it paused. 

ssb thread: [%aRW15BMIi/tbpv8wj6WN6hHFZymTS6bqWtroNDoMOVw=.sha256](https://viewer.scuttlebot.io/%25aRW15BMIi%2Ftbpv8wj6WN6hHFZymTS6bqWtroNDoMOVw%3D.sha256)
