### ISSUE TITLE
Error: Server has no public ip address, cannot create useable invitation

### ISSUE THREAD

**Issue by cryptix** [ssbc/scuttlebot#260]
This particular node is on the freifunk network from hamburg. It has an internal (to the freifunk network) IPv4 addresses (ex: `10.112.49.125/18`) and externally reachable ipv6 address.

I'd like to hand out invites for both.

**Comment by dominictarr** [comment]
oh, you can overide that with `--allowPrivate` option.
it ought to take the ipv6 address...

It might be easiest if you make a pull request, since you have access to the server with this behaviour.
It's something in here: https://github.com/ssbc/scuttlebot/blob/master/plugins/invite.js#L50-L57

I'm not sure whether that will return a ipv4 or 6 address. possibly you need to tell it to use the ipv6 address?
when starting the server? (that happens here: https://github.com/ssbc/secret-stack/blob/master/index.js#L102)

**Comment by cryptix** [comment]
I couldn't figure out where to apply `--allowPrivate` as a flag (It was either ignored or raised an error). What did work for was setting up a `$HOME/.ssb/config`, with `{ "allowPrivate":true}`.

I came across another problem in Patchwork where it failed to parse `[...v6addr..]:port@...` invites, which I circumvented with a `/etc/hosts` entry for the moment. I'll open an issue on that repo.
