### ISSUE TITLE
No type filter in createUserStream

### ISSUE THREAD

**Issue by arj03** [ssbc/scuttlebot#322]
I was wondering why createUserStream has no type filter. It has filters on keys so I would think it has on type as well.

I saw that messagesByType exists, but it might be a good idea to add it to createUserStream as well as messagesByType only works on the "current" user.

**Comment by pfraze** [comment]
This is because the methods that Scuttlebot gives are only for pre-computed indexes. Since precomputing the index gives a certain performance guarantee, that is higher than scan-and-filter, we thought it would be better to adopt this policy. Then, if you want to do the filtering by type, you can do it yourself, and have the exact same results:

```js
pull(
  sbot.createUserStream({ id: bobsId }),
  pull.filter(function (msg) { return msg.value.content.type == 'post' }),
  // ...
)
```

But we also recognize that's an uber pain, so @dominictarr is working on a plugin which will allow much easier generalized queries.

**Comment by dominictarr** [comment]
https://github.com/dominictarr/streamview-links currently gives you SQL like queries (select, where, group, at least not join yet)

**Comment by dominictarr** [comment]
that will be coming soon... but lots else to do

**Comment by arj03** [comment]
Thanks. Glad to know I'm using the API correctly :)
