### ISSUE TITLE
invite doesn't understand --port

### ISSUE THREAD

**Issue by du5t** [ssbc/scuttlebot#336]
how to reproduce:

1. checkout master, `npm install`, `./bin.js server`, break now that manifest is initialised
2. run `./bin.js server --host foo --port SOME_LARGE_PORT`
3. from other session, run `./bin.js --port SAME_LARGE_PORT invite.create 1`

```
/home/user/scuttlebot/plugins/invite.js:81                     
          else cb(null, addr + '~' + seed.toString('base64'))            
               ^                                                         
                                                                         
TypeError: cb is not a function                                          
    at /home/user/scuttlebot/plugins/invite.js:81:16
```

line 81 seems to be looking for an error callback.

**Comment by pfraze** [comment]
The usage is in step 3 wrong. The `--port n` switch is going to be passed into `invite.create` as a parameter to that method, which it's not expecting. That's causing the crash.

The issue is: our input validation only checks the parameters that are passed -- it does *not* validate the number of parameters. So, your usage actually translates to the following call, in JS:

```js
invite.create(1, { port: ... }, cb)
```

When the create function is expecting `(1, cb)`.

So, two action points: 
 1. We need to update our validators to check the number of parameters.
 2. You need to fix your usage in step three. Use an env var instead of a switch. `ssb_port=N ./bin.js invite.create 1`

**Comment by pfraze** [comment]
Actually, my first action point may not be needed. It looks like the correct usage is output by scuttlebot on this error. That's the intended result.
