### ISSUE TITLE
Duplicate entries in the sync page

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#341]
![screen shot 2016-04-19 at 10 18 08 am](https://cloud.githubusercontent.com/assets/1270099/14644538/0a2280c0-0618-11e6-8306-2e14d4f887d7.png)

Here's a dump of the peers: https://gist.github.com/pfraze/b4ae4b3b4b692dc672092a9eb0d1358d
(Dump was not taken exactly when the screenshot was, but close.)

**Comment by dominictarr** [comment]
there are some cases where the same host is a pub with multiple keys, or (maybe) a key has been copied.

**Comment by pfraze** [comment]
Yeah, search for `@uRECWB4KIeKoNMis2UYWyB2aQPvWmS3OePQvBj2zClg=.ed25519` in that peers.json and you can see the entry is there under different hostnames

**Comment by dominictarr** [comment]
if the peers list was persistent, we could just drop out peers that havn't worked for a timeperiod (say, 1 week)

if we gossiped the peers list, then it would no longer be directly coupled to the pub anouncements (though am not suggesting removing those) and then if a old peer came back on line you could learn about that from a peer you connected to.

Also this would be a step towards having true p2p via utp, etc

**Comment by pfraze** [comment]
> if the peers list was persistent, we could just drop out peers that havn't worked for a timeperiod (say, 1 week) 

in some cases that would work, and that would be an improvement overall. it wouldnt solve some other cases. the key I copied above is a difference of IP vs hostname, and both connect

> if we gossiped the peers list, then it would no longer be directly coupled to the pub anouncements (though am not suggesting removing those) and then if a old peer came back on line you could learn about that from a peer you connected to.

what's the advantage? we'd ultimately be pulling from the same source data, wouldnt we?

**Comment by dominictarr** [comment]
at times it may be possible to have the same key available via different hostnames, the gossip plugin cares more about hostnames, because it's gotta try the different routes to a peer. maybe the solution is just for the ui to show the successful connections by key, not host.

there are lots of old pubs that have been offline for a long time, connecting to all of them every startup just to see which ones are active is gonna get more expensive as time goes on. If you could announce a temporary peer via another means it would make the protocol more flexible.

Maybe I should clarify about what I mean by "gossiping the peer list" I don't mean putting it in the secure log, just having a public access to gossip.peers (or simpler) so I can see what peers you are using.

**Comment by pfraze** [comment]
> Maybe I should clarify about what I mean by "gossiping the peer list" I don't mean putting it in the secure log, just having a public access to gossip.peers (or simpler) so I can see what peers you are using.

ok, in which case youd include information about which are active

**Comment by dominictarr** [comment]
yes, probably just limit the list to who is currently active, that way if I change ip addresses temporarily i can tell everyone
