### ISSUE TITLE
peer hello fail blocks server

### ISSUE THREAD

**Issue by donpdonp** [ssbc/scuttlebot#404]
after $ sbot invite.accept 'ssb.hypersignal.xyz:8008:@..
the server gets hung up talking to hypersignal and other peers
```
Disconnected ssb.hypersignal.xyz:8008:@XRg7...=.ed25519
Connected ssb.hypersignal.xyz:8008:@XRg7...=.ed25519
Disconnected ssb.hypersignal.xyz:8008:@XRg7...=.ed25519

Error: expected hello
    at abort (/home/donp/projects/scuttlebot/node_modules/secret-handshake/protocol.js:80:45)
```

The server blocks on this so any other sbot commands result in "Error: Could not connect to the scuttlebot server." If I'm very lucky, an sbot command will get through to the local server and I have verified there are many peers listed. Seems like the problem with this one peer is effectively taking down the local server.

**Comment by dominictarr** [comment]
what you could try, is disable gossip temporarily, if you start sbot with `--no-gossip.global` that should stop making any replication connections to hypersignal (and others) you'll need to restart in order to replicate though, but if your instance already knows about some peers it must have already replicated some though right?
