### ISSUE TITLE
prebuild-install issue

### ISSUE THREAD

**Issue by loveloso** [ssbc/scuttlebot#405]
I am trying to install scuttlebot on Ubuntu 16.
Installation fails after running "sudo npm install -g scuttlebot" command as screenshot below:
![image](https://cloud.githubusercontent.com/assets/6879069/26521902/7be069fe-4337-11e7-93f2-872646c1a05d.png)

This is the npm-debug.log output:
![image](https://cloud.githubusercontent.com/assets/6879069/26521910/a5203fec-4337-11e7-9271-ec7077da9648.png)

Any ideas?

**Comment by dominictarr** [comment]
oh, did you install node with apt-get? unfortunately their overly strict approach to packaging means that their modules is generally out of date and the recommended way to install node is with something like: https://github.com/creationix/nvm

it looks like you are on node@4 that is really really old, Long Term Support is now node@6

that also lets you keep multiple versions of node on your system, and switch between them easily!

ps, it's better if you just copy and past the text, instead of screenshots. then if someone needs to search an error message they can do it easily.

**Comment by loveloso** [comment]
Thanks Dominic. I will follow your link and try to update to node 6. Sorry about the screenshots. I will copy and paste the text here when I have a chance to connect to my VM again.

**Comment by dominictarr** [comment]
@loveloso no problem!

**Comment by loveloso** [comment]
I did this and it works now:
sudo apt-get update && sudo apt-get -y upgrade 
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - 
sudo apt-get install -y nodejs
sudo npm install -g scuttlebot

**Comment by dominictarr** [comment]
awesome!
