### ISSUE TITLE
Encryption is hardcoded?

### ISSUE THREAD

**Issue by Seswu** [ssbc/scuttlebot#539]
Hello, I've been thinking about making an application for secure scuttlebot, but it seems as if the encryption protocol is hardcoded?

Is there a plan to change this design to accomodate use cases where other encryption algorithms would be preferred, or is this approach chosen because it is the only one fitting to secure scuttlebots unique networking design?

**Comment by arj03** [comment]
Hi @Seswu. What exactly do you mean with encryption protocol. Do you mean secret handshake? Or the way messages are structured?

**Comment by dan-mi-sun** [comment]
@Seswu @arj03 the mmt::darkcrystal team has applied for a grant from the ethereum foundation. one of the first jobs which we would do would be to work with dom to refactor this so that ssb can start using `secp256k` in the process this would also open up to other encryption schemes :) We should hear about the grant within the next couple of weeks.

**Comment by dominictarr** [comment]
basically: yes, we've given thought to how we'd upgrade the various encryption protocols, and it would probably take a bit of refactoring, but there are things in place to enable it. for example, all the cypher tokens (feed/message ids) end in a tag of the type of algorithm they use .ed25519 and .sha256
the encryption protocol to be used in a p2p connection is included as part of the _address_ via https://github.com/ssbc/multiserver so we can roll out another protocol by just listening on another port side by side the old one (and discontinuing the old one at some point)
