### ISSUE TITLE
trusting 'pub' messages

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#68]
somebody could be a real jerk and flood your feed with bad pub messages. should we consider only using the pub messages of trusted peers?

**Comment by dominictarr** [comment]
maybe a pub message could be signed by the pub server, and then if you connect to that peer and it's a different pub, then you disregard that pub message. So if someone posted an invalid pub, it wouldn't get connected to more than once.

The threat here is you do not want anyone to be able to fool the network into performing a ddos attack on a pub server for you.

Hmm, I think if every peer only attempted to connect to an invalid pub once, then that should mostly work.

**Comment by dominictarr** [comment]
unless millions of peers see your pub message...

we probably need some sort of backoff strategy about not overloading pub servers too much.

**Comment by pfraze** [comment]
hmm we may need to give that some thought. i hadnt thought of using it to perform a ddos.

**Comment by pfraze** [comment]
if users had to explicitly choose their pub servers via the cli/gui, there'd be less chance of an attack via this vector. pub messages would advertise options for other users to consider

this makes the network less automagic, but could be a positive for privacy since the peers you contact will know 1 that you're online and 2 what feeds you're requesting. it could also help users reason about their connectivity with each other; for instance, if i'm using the grimwire pub server then i know i'm subscribed to the "grimwire community" and will get the messages of its members

**Comment by dominictarr** [comment]
I think it would be easiest to start with just-works automagic and then add security by adding observability and constraining it. So, as long as we have a plan for privacy, we should begin by making it just work at first.

**Comment by pfraze** [comment]
with this i'm more concerned about runaway resource usage than privacy. can you see a scenario where auto-connecting to announced pubs would be safe?

ignoring the ddos issue, ignoring the 'bad entry' floods that would make peers try connecting to nonsense locations...

the best balance
 - maximises data availability
 - minimizes the number of realtime connections
 - minimizes the amount of caching required
 - minimizes the number of cache-hops for a piece of data to reach interested parties

what's the overhead of a polling connection vs the overhead of caching data? if we reduce the number of polling connections, then we'll need pubs/peers to do more caching. without running the numbers, i'd assume a lan of 10 nodes would be better off if they formed a ring of 2 connections each instead of a fully-connected network. it'd take data longer to distribute data, but there'd be less network polling

would the same principle be true for pub-servers? would they be better off with a smaller set of polling peers, even if that meant they need to cache more data overall on their clients' behalf? (client, in this case, being peers that rely on pubs to reach the global network)

when you analyzed availability as a function of connectedness, you found something like 2 connections per node was a sweet-spot, yeah? how might that apply here?

**Comment by dominictarr** [comment]
okay so if we are just talking about data desimination efficiency then that is different to trusting network efficency. That is about how peers respond to the pub messages. There is not really anything wrong with how we currently do pub messages from this perspective, but the gossip strategy _could_ be improved.

There is so many ways that could be done though... prehaps it is more important to gather metrics about how much bandwidth is used/wasted/useful so that when we make future improvements we'll be able to know how well we did.

A ring is quite efficient in terms of bandwidth, but it's fragile, because if one peer drops out then it will break the ring. Also, you need coordination to build the ring. I learnt a lot by attending this: https://www.youtube.com/watch?v=RV4f5vHFavs

David's uses randomized networks because then every node can act individually without having to coordinate, or know where they are in the topology of the network.

With a random network then the properties (like mean distance between nodes) won't be effected much if peers go down. etc.

Also, different peers may want to employ different strategies because of different constraints. For example, a phone will want a strategy that conserves power, but a pub server may want to optimize for latency, etc, etc

**Comment by pfraze** [comment]
> okay so if we are just talking about data desimination efficiency then that is different to trusting network efficency

i think theyre related in overall strategy. we have peers auto-connecting to announced pub because that maximizes connectivity, because that maximizes dissemination. but autoconnecting violates the security perimeter design principle (do not leave without deliberate and explicit user action) and i think that's the core of our problems. if we could refocus our strategy so that peers dont autoconnect but still get high dissemination, we'd reduce the problem

randomized connection sounds good, but maybe just to those chosen by explicit user action. it's automatic connection (even to pubs announced by trusted peers) that i can't ever see as being safe, since it's such a good ddos vector

**Comment by dominictarr** [comment]
I'm a little confused about what you are arguing for - in https://github.com/ssbc/scuttlebot/issues/68#issuecomment-69514322 you said you where more worried about resource usage than privacy, but in 
https://github.com/ssbc/scuttlebot/issues/68#issuecomment-69606298 you seem to be arguing for security?

I disagree that this constitutes leaving the security perimeter because it's not communicating over an arbitary protocol (or pulling down arbitary code, flash etc) it's communicating only over a predefined protocol (ssb protocol)

If users had to select which pub servers they wanted to connect to it would be annoying and confusing. If you didn't approve the right things it would just sort of silently stop working, and not be obvious why, which would make people want to not use ssb.

Okay getting back to the original idea of this issue, ignoring pub messages created by bad users is a good idea, as long as it still works automagically.

**Comment by pfraze** [comment]
i think resource usage and privacy are both security matters. a ddos is an attack on resources, while eaves-dropping (in this case, by getting the user to connect to a listener) is an attack on privacy. my point was that i think the privacy attack is something we can deal with later, but the resource attack is not because a resource attack could make the network infeasible

that line of thinking extended further in https://github.com/ssbc/scuttlebot/issues/68#issuecomment-69514322 to non-malicious usage, where i'm wondering if a pub that goes viral would need to expect the entire network to start reaching it

> I disagree that this constitutes leaving the security perimeter

i believe this is leaving the security perimeter because it's creating outbound traffic without user approval, similarly to how embedding an image would. the security implications are almost identical to image embeds - both can be used to surveil or trigger a ddos

> If users had to select which pub servers they wanted to connect to it would be annoying and confusing

i disagree that the ux of choosing your peers has to be bad (this was my point in https://github.com/ssbc/scuttlebot/issues/68#issuecomment-69506393) but i agree it's less good than automagic

if we only used pubs announced by trusted peers, i'd be more ok with that than trying to filter out pubs announced by flagged peers. (i prefer default deny to default allow.) but i'd still be a bit concerned about ddos attacks via pub messages until i knew for sure how far-reaching a trusted user can be (that is, how many peers would obey a pub message published by them)

**Comment by pfraze** [comment]
perhaps we just need to implement proper throttling so that connecting nodes dont overload anybody, and nodes receiving connections can reject connections according to their workload

**Comment by pfraze** [comment]
and i'd suspect we'd want to track a peer's workload as well as the aggregate workload to make sure a selfish peer cant tie up a node

**Comment by pfraze** [comment]
if i felt confident in the throttling than i'd be ok with default allow (for handling resource-usage security)

**Comment by dominictarr** [comment]
Okay so I think we agree on what the objective are here, but the question is how to best achive them.
To summarize: 

* it must not be possible to manipulate the network into wasting resources (denial of service attack)
* it must not be possible to trick peers into leaking information about themselves (privacy)

That is something we'll discover via building it out.

Yeah, resource management will largely be about throttling etc.

Also, idea: we could make connecting to a pub more private by waiting for the pub to auth first,
and disconnecting if the pub was invalid (using something like the authorized pub cert I proposed above)
for local connections, authorization would still be simultanious.

**Comment by dominictarr** [comment]
oh yeah, I guess my concerns here are about bootstrapping new users into the network. When you are new you have less to loose, and so less privacy is okay (you don't have a large identity yet) so using a different strategy at first (because you won't have set trusted peers until you have used the system for a bit)

**Comment by pfraze** [comment]
ok sounds like we're synced. pub-auth-first does sound like a good strategy

maybe we should setup a checklist of protocol tasks/issues and possible strategies that we can track? more fine-grained stability status
