### ISSUE TITLE
Wiki list of public rooms has 3 dead links

### ISSUE THREAD

**Issue by davidbaunach** [ssbc/scuttlebot#765]
The first 3 rooms listed in the wiki page for public rooms are offline. I'm not sure of the protocol for updating the wiki, can I add a timestamp and a advisory to those three that they are offline? Or is there someone else who should take care of that?

**Comment by decentral1se** [comment]
Hey @davidbaunach! Thanks for taking a look. It's a pretty good question you're raising and I'm not quite sure. From my perspective, there is acknowledgement that there's some docs chaos across the ecosystem, so this might be an opportunity to shore some of that chaos up. I could edit the wiki myself with your suggestions but idk if that is great because yeh, this stuff is just languishing here, no? Idk if you wanna go down the rabbit hole of docs with me but I'm well up for hearing thoughts if you are :smile:

**Comment by mplorentz** [comment]
@davidbaunach in the past I've made a good faith effort to contact the admin (or in some cases find contact info for the admin), waited about a week, then moved the listings to the "inactive" heading. This was with pubs but if you'd like to do the same with rooms I that would be great. The admins can always revert the changes if they bring their room back up.

**Comment by davidbaunach** [comment]
Hey @decentral1se guess a little chaos isn't a bad thing, but yeah if there's anything I can do to help I'm willing. I'm just a hobbyist when it comes to this stuff, but I love the project, so anything I can do I'm up for!

Hey @mplorentz the third one popped back into existence, so I guess I might wait a little bit more before I do anything, but maybe a month from now if the top two are still dead I might try to find the admins and go from there!
